version: '2'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - logs:/var/log/odoo/
      - addons_zip:/mnt/addons-zip
      - addons_links:/mnt/addons-link
      - ./config:/etc/odoo
      - ./odoo_addons:/mnt/extra-addons
  web_test:
    image: odoo:13.0
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "9069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - logs_test:/var/log/odoo/
      - addons_zip_test:/mnt/addons-zip
      - addons_links_test:/mnt/addons-link
      - ./config_test:/etc/odoo
      - ./odoo_test_addons:/mnt/extra-addons
  db:
    image: postgres:10
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
  logs:
  logs_test:
  addons_zip:
  addons_links:
  addons_zip_test:
  addons_links_test:
